using System.Collections;
using System.Collections.Generic;
using UnityEngine.SceneManagement;
using UnityEngine;

public class GameManager : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void StartGame()
    {
        SceneManager.LoadScene("Level01");
    }

    public void ExitGame()
    {
        Application.Quit();
    }

    public void ReturnToMenu() 
    {
        SceneManager.LoadScene("MainMenu");
    }

    public void LoadNextScene()
    {
        
    }

    public void PauseGame()
    {
        Time.timeScale = 0.0f;
    }

    public void UnpauseGame()
    {
        Time.timeScale = 1.0f;
    }    
}
